# Use postgres/example user/password credentials
version: '3.9'

services:

  jupyter:
    build:
      dockerfile: Dockerfile.jupyter
      context: .
    ports:
      - 8889:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./taxi-data:/home/jovyan/taxi-data:ro
    command: start-notebook.py --NotebookApp.token='my-token'

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: taxi_db
    ports:
      - 5432:5432
